### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by tanepiper** [takeoff-env/takeoff-blueprint-basic#2]

**Comment by sahalsaad** [comment]
Hi, I interested in this but no idea how to run this project.
What is the easiest way to run this project ?

**Comment by tanepiper** [comment]
@sahalsaad Please check out the documentation for Takeoff at https://github.com/takeoff-env/takeoff

**Comment by sahalsaad** [comment]
@tanepiper This look weird. 
![](https://i.imgur.com/zKtgKHM.png)

I followed the `4 easy steps`.

**Comment by tanepiper** [comment]
@sahalsaad yes I'm aware of this. The underlying react example needs refactoring as the styling broke but the underlying example still works (the login button is in the top right and will show an admin menu).

Unfortunately I have not had time in the last week to look at this, I am also working on takeoff-env/takeoff#27 but at the moment I'm the sole developer working on this so these are two rather large tasks.
